# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 06:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0008_alter_user_username_max_length'),
        ('taggit', '0002_auto_20150616_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaScene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Object created date')),
                ('updated', models.DateTimeField(auto_now=True, help_text='Object update date')),
                ('access', models.PositiveSmallIntegerField(choices=[(0, 'Private'), (1, 'Public')], default=0, help_text="((0, 'Private'), (1, 'Public')) ")),
                ('name', models.CharField(help_text='Scene name (must be uniq) ', max_length=64, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SceneRevision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Object created date')),
                ('updated', models.DateTimeField(auto_now=True, help_text='Object update date')),
                ('access', models.PositiveSmallIntegerField(choices=[(0, 'Private'), (1, 'Public')], default=0, help_text="((0, 'Private'), (1, 'Public')) ")),
                ('description', models.CharField(blank=True, help_text='Like a commit-message', max_length=256, null=True)),
                ('gl_program', models.TextField(blank=True, help_text='Program in JSON', null=True)),
                ('gl_params', models.TextField(blank=True, help_text='Params in JSON', null=True)),
                ('child', models.ForeignKey(blank=True, help_text='Reference to child revision', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_id', to='api.SceneRevision')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, help_text='Object created date')),
                ('updated', models.DateTimeField(auto_now=True, help_text='Object update date')),
                ('user', models.OneToOneField(help_text='Reference to user id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('description', models.TextField(blank=True, help_text='Small info about user', null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='scenerevision',
            name='owner',
            field=models.ForeignKey(help_text='Reference to user id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scenerevision',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Reference to parent revision', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_id', to='api.SceneRevision'),
        ),
        migrations.AddField(
            model_name='scenerevision',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='Comma-separated string of tags', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='metascene',
            name='owner',
            field=models.ForeignKey(help_text='Reference to user id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='metascene',
            name='revision',
            field=models.OneToOneField(blank=True, help_text='Reference to current version of Scene', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.SceneRevision'),
        ),
        migrations.AddField(
            model_name='metascene',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='Comma-separated string of tags', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
