# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-08 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20161125_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metascene',
            name='access',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Private'), (1, 'Public')], default=0, help_text=" ((0, 'Private'), (1, 'Public')) "),
        ),
        migrations.AlterField(
            model_name='scenerevision',
            name='access',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Private'), (1, 'Public')], default=0, help_text=" ((0, 'Private'), (1, 'Public')) "),
        ),
    ]
